# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-27 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookportal', '0002_books_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='lijo', max_length=500),
        ),
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/files/resume.pdf', upload_to='files'),
        ),
    ]
